name: solid
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Marcos Mota <marcos@treeinova.com.br>

environment:
    sdk: '>=2.5.0 <3.0.0'

dependencies:
    dio: ^3.0.2

dev_dependencies:
    pedantic: ^1.8.0
    test: ^1.6.0
